micronaut:
    application:
        name: complete
#Uncomment to set server port
    server:
        port: 8080
#tag::datasource[]
datasources:
    default:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ""
        driverClassName: org.h2.Driver
#end::datasource[]